language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get install -qq postgis
before_script:
  - psql -c 'CREATE DATABASE postgis_adapter_test;' -U postgres
  - psql -d postgis_adapter_test -c "CREATE EXTENSION postgis;" -U postgres
script: bundle exec rake test
